<a href="https://colab.research.google.com/github/hiro106/numpy_learning/blob/main/numpy_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

In [ ]:
import numpy as np

In [ ]:
a = np.zeros((10, 2))

In [ ]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
b = a.T

In [ ]:
b   

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
c = b.view()

In [ ]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# About the difference between view and copy
# https://numpy.org/doc/stable/user/basics.copies.html